### PR TITLE
fix: update type of some field of Project struct to match response from deps.dev API

### LINKED ISSUE #70: Project structure contains field with wrong type
**Describe the bug**

Some field of the Project struct have changed type on deps.dev service and are not updated in this library.
[Fields are](https://github.com/edoardottt/depsdev/blob/d19b20cf6a023083cad2a32e06e4d4dbfb3e183a/pkg/depsdev/project.go#L21C2-L23):
- OpenIssuesCount
- StarsCount
- ForksCount

They all should be integer instead of string.

**To Reproduce**
1. Check response from API call of `getProject` endpoint:
- https://api.deps.dev/v3/projects/github.com%2Ffacebook%2Freact
- https://api.deps.dev/v3/projects/github.com%2Fedoardottt%2Fdepsdev

**Expected behavior**
This library should update the type of the field to string so it can properly decode the json sent by deps.dev API.

### PR DESCRIPTION
**Pull request by zaibon**
fixes #70

### CODE REVIEW

**Comment by edoardottt** [comment]
Hi @zaibon. I've changed the base form main to devel. There are some conflicts that need to be resolved.

**Comment by zaibon** [comment]
@edoardottt Thanks, I've didn't see the devel branch. So I've rebased on it and fixed the conflict.

File: pkg/depsdev/v3/api_test.go [hunk 1]
```diff
@@ -21,13 +21,40 @@ import (
...
 	"github.com/edoardottt/depsdev/pkg/depsdev/v3"
+	"github.com/stretchr/testify/assert"
 	"github.com/stretchr/testify/require"
 )
 
 var (
 	api = depsdev.NewV3API()
 )
 
+func TestGetProject(t *testing.T) {
```
Comment (edoardottt) [inline pkg/depsdev/v3/api_test.go:32]: Unreliable. If someone stars the repo or fork it the test will fail

File: pkg/depsdev/definitions/project.go [hunk 2]
```diff
@@ -18,9 +18,9 @@ import "time"
 
 type Project struct {
 	ProjectKey      ProjectKey `json:"projectKey,omitempty"`
-	OpenIssuesCount string     `json:"openIssuesCount,omitempty"`
-	StarsCount      string     `json:"starsCount,omitempty"`
-	ForksCount      string     `json:"forksCount,omitempty"`
+	OpenIssuesCount int        `json:"openIssuesCount,omitempty"`
```
Comment (edoardottt) [inline pkg/depsdev/definitions/project.go:21]: It would be better to change all the occurences of this issue. For example, https://github.com/edoardottt/depsdev/blob/d19b20cf6a023083cad2a32e06e4d4dbfb3e183a/pkg/depsdev/project.go#L53 should be a number as far as I can see in the docs.  
What do you think?

**Review by edoardottt — CHANGES_REQUESTED** [review]

File: pkg/depsdev/definitions/project.go (hunk 2 above)
Comment (edoardottt) [reply pkg/depsdev/definitions/project.go:21]: references: https://docs.deps.dev/api/v3/

File: pkg/depsdev/v3/api_test.go (hunk 1 above)
Comment (zaibon) [reply pkg/depsdev/v3/api_test.go:32]: Make sense, I've updated the test to skip comparing actual value.

File: pkg/depsdev/definitions/project.go (hunk 2 above)
Comment (zaibon) [reply pkg/depsdev/definitions/project.go:21]: I've added some other type fixe I could find. Any other I've missed?
